"""
adversary/adversary_agent.py

An LLM-powered agent that reads git diffs,
updates the knowledge base, and generates new regression tests.

Requires GOOGLE_API_KEY to be set in .env or environment.
"""
import os
import sys
import json
import re
from datetime import date
from dotenv import load_dotenv

load_dotenv()
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ADVERSARY_DIR = os.path.dirname(os.path.abspath(__file__))
KNOWN_ISSUES_PATH = os.path.join(ADVERSARY_DIR, "known_issues.json")
TEST_FILE_PATH = os.path.join(ADVERSARY_DIR, "test_regression.py")

def _call_llm(prompt: str) -> str:
    """Calls Gemini Flash with the given prompt. Falls back gracefully if no API key."""
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        print("[ADVERSARY] No GOOGLE_API_KEY found — skipping LLM analysis. Regression tests will still run.")
        return ""
    try:
        import litellm
        response = litellm.completion(
            model="gemini/gemini-2.5-flash",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3
        )
        return response.choices[0].message.content
    except Exception as e:
        print(f"[ADVERSARY] LLM call failed: {e}. Regression tests will still run.")
        return ""

def load_knowledge_base() -> dict:
    with open(KNOWN_ISSUES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)

def save_knowledge_base(kb: dict):
    kb["last_updated"] = str(date.today())
    with open(KNOWN_ISSUES_PATH, "w", encoding="utf-8") as f:
        json.dump(kb, f, indent=2)

def analyze_diff_and_update(diff: str, codebase_summary: str) -> dict:
    """
    Sends the git diff to the LLM and asks it to:
    1. Identify new fragile areas introduced by this change.
    2. Generate new pytest test functions to guard against regression.
    Returns a dict: {"new_fragile_areas": [...], "new_tests": "...python code..."}
    """
    if not diff or diff.startswith("(No"):
        return {}

    kb = load_knowledge_base()
    existing_issues = "\n".join(f"- {i}" for i in kb["fragile_areas"])

    prompt = f"""You are an adversarial QA agent for a Python CLI quiz game.

The codebase structure is:
{codebase_summary}

The developer just made this change:
```diff
{diff[:6000]}
```

Existing known fragile areas (already covered by tests):
{existing_issues}

Your task:
1. LIST any NEW fragile areas introduced by this change that are NOT already covered above. Be specific.
2. WRITE 1-3 new pytest test functions (ready to copy-paste) that guard against regressions from this change.
   - Import from state, database, or agents as needed.
   - Use `sys.path.insert(0, ROOT)` style is already handled.
   - Do NOT re-test already listed issues.

Respond ONLY with valid JSON in this exact format:
{{
  "new_fragile_areas": ["area1", "area2"],
  "new_tests": "def test_example():\\n    assert True"
}}

If there are no new fragile areas, return empty lists/strings."""

    raw = _call_llm(prompt)
    if not raw:
        return {}

    # Extract JSON from response (handle markdown code blocks)
    json_match = re.search(r'\{[\s\S]*\}', raw)
    if not json_match:
        print(f"[ADVERSARY] Could not parse JSON from LLM response.")
        return {}

    try:
        result = json.loads(json_match.group())
        return result
    except json.JSONDecodeError as e:
        print(f"[ADVERSARY] JSON parse error: {e}")
        return {}

def apply_updates(analysis: dict):
    """Merges new fragile areas into known_issues.json and appends new tests to test_regression.py."""
    if not analysis:
        return

    new_areas = analysis.get("new_fragile_areas", [])
    new_tests_code = analysis.get("new_tests", "").strip()

    if new_areas:
        kb = load_knowledge_base()
        existing = set(kb["fragile_areas"])
        added = [a for a in new_areas if a not in existing]
        kb["fragile_areas"].extend(added)
        save_knowledge_base(kb)
        for area in added:
            print(f"[ADVERSARY] 📌 New fragile area logged: {area}")

    if new_tests_code:
        with open(TEST_FILE_PATH, "a", encoding="utf-8") as f:
            f.write(f"\n\n# ─── Auto-generated by Adversary Agent ({date.today()}) ────────────────\n")
            f.write(new_tests_code)
            f.write("\n")
        print(f"[ADVERSARY] ✏️  New test(s) appended to test_regression.py")

if __name__ == "__main__":
    from observer import get_unstaged_diff, summarize_codebase
    diff = get_unstaged_diff()
    summary = summarize_codebase()
    print("[ADVERSARY] Analyzing changes...")
    analysis = analyze_diff_and_update(diff, summary)
    apply_updates(analysis)
    print("[ADVERSARY] Knowledge base update complete.")
